defaults:
  run:
    shell: bash
    working-directory: packages/vue-sweetalert2

on: pull_request

name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: cd packages/vue-sweetalert2
    - run: yarn
    - run: yarn test
